language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests on script and regression tests on notebook
script: 
  - pip install pytest pytest-cov pytest-azurepipelines
  - python -m pytest --doctest-modules example --cov=example --cov-report=xml